services:
  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
